"""empty message

Revision ID: 2a68646e41cf
Revises: 41def301c5c6
Create Date: 2023-10-25 09:39:16.736367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2a68646e41cf"
down_revision: Union[str, None] = "41def301c5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "encodings",
        "data",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.LargeBinary(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "encodings",
        "data",
        existing_type=sa.LargeBinary(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
